import React from 'react';
import styles from './style.module.scss';
import '../../app/index.css';
import Button from '../button/Button';
export default function ProductsWidget() {
    return (React.createElement("section", { className: styles.productsWidget },
        React.createElement("div", { className: styles.content },
            React.createElement("div", { className: styles.iphone },
                React.createElement("div", { className: 'container' },
                    React.createElement("div", { className: styles.iphoneIn },
                        React.createElement("div", { className: styles.description },
                            React.createElement("p", null, "Pro.Beyond."),
                            React.createElement("h2", { className: styles.iphoneText },
                                "IPhone 14 ",
                                React.createElement("h2", { className: styles.pro }, " Pro")),
                            React.createElement("p", { className: styles.iphoneTxt }, "Created to change everything for the better. For everyone"),
                            React.createElement(Button, null)),
                        React.createElement("div", { className: styles.iphoneImg })))),
            React.createElement("div", { className: styles.anotherProducts },
                React.createElement("div", { className: styles.products },
                    React.createElement("div", { className: styles.playStation },
                        React.createElement("div", { className: styles.playStationImg }),
                        React.createElement("div", { className: styles.playStationIn },
                            React.createElement("h3", { className: styles.playStationText }, "Playstation 5"),
                            React.createElement("p", { className: styles.playStationTxt }, "Incredibly powerful CPUs, GPUs, and an SSD with integrated I/O will redefine your PlayStation experience."))),
                    React.createElement("div", { className: styles.appleProduct },
                        React.createElement("div", { className: styles.appleProductImg }),
                        React.createElement("div", { className: styles.appleProductIn },
                            React.createElement("h3", { className: styles.appleProductText },
                                "Apple AirPods ",
                                React.createElement("h3", { className: styles.bold }, "Max")),
                            React.createElement("p", { className: styles.appleProductTxt }, "Computational audio. Listen, it's powerful"))),
                    React.createElement("div", { className: `${styles.appleProduct} ${styles.appleProduct2}` },
                        React.createElement("div", { className: styles.appleProductImg }),
                        React.createElement("div", { className: styles.appleProductIn },
                            React.createElement("h3", { className: styles.appleProductText },
                                "Apple ",
                                React.createElement("br", null),
                                " Vision ",
                                React.createElement("h3", { className: styles.bold }, "Pro")),
                            React.createElement("p", { className: styles.appleProductTxt }, "An immersive way to experience entertainment")))),
                React.createElement("div", { className: styles.macBook },
                    React.createElement("div", { className: styles.macBookIn },
                        React.createElement("h4", { className: styles.macBookText },
                            "Macbook ",
                            React.createElement("h4", { className: styles.bold }, "Air")),
                        React.createElement("p", { className: styles.macBookTxt }, "The new 15\u2011inch MacBook Air makes room for more of what you love with a spacious Liquid Retina display."),
                        React.createElement(Button, null)),
                    React.createElement("div", { className: styles.macBookImg }))))));
}
